### ISSUE TITLE
Awesome package! But i have a suggestion

### ISSUE THREAD

**Issue by labo-css** [jrattray13/swackets#1]
First off, i'm really astonished i never saw something like that before, this is really good.
But the renderering kinda bother me, i like my brackets to be bright white, so i can see them.
What about introducing a setting where you can choose where the color is applied? In the bracket itself, on a background behind the bracket, an underline or even in the gutter.

I searched a bit in the source code and i don't know how to use JS, i only can help with the css part.

**Comment by jrattray13** [comment]
Thanks for your suggestion, i'll look into changing it into a default line under with option to change to full color.

With under line being coloured instead should be less rendering since it is a Atom api decoratio so perhaps it will be more responsive & improved. But idk I do like the full bracket color once you get used to it at a glance is great info fast. But nothing wrong with options :+1:

**Comment by labo-css** [comment]
Thanx :+1:

**Comment by lexicalunit** [comment]
Oh hay, I didn't notice this issue before I submitted #4. Should resolve this issue :)

**Comment by jrattray13** [comment]
@labo-css I have looked into decorations this weekend (underline/highlight braces) to no success. First it looked 'off' you couldnt really achieve the same affect as I intended with swackets, underline barely visible and highlight/background too visible. Second since decorations api requires regex to identify where to place markers it showed the highlighting/underline for commented braces too, which again looked dodgy.

So unfortunately I will not be adding support for other methods except coloured braces -UNTIL atom potentially adds coloured braces to their decoration api and i'll work around regex issues somehow (braces in strings hmmmm). Sorry, but now you can choose your own colours at least so perhaps that will aid you :smile: Sorry I couldnt be of more help
