### ISSUE TITLE
Add parentheses and brackets

### ISSUE THREAD

**Issue by alexchandel** [jrattray13/swackets#16]
This package would be *extremely* useful for lisp, except that lisp uses parentheses (and optionally brackets in Scheme).

Please add the option to rainbow these as well.

**Comment by jjcomer** [comment]
+1

**Comment by CiaranReen** [comment]
+1

**Comment by evgenykochetkov** [comment]
+1

**Comment by alexchandel** [comment]
@jrattray13 Quite a popular issue.

Also related: #11 and #12

**Comment by maackle** [comment]
If merged, this is going to make this package very popular with the lisp/Clojure community. Currently there is no other "rainbow parens" package for Atom.

**Comment by alexchandel** [comment]
@maackle unfortunately @ibraimgm needs to rebase (and update) his pull request on #12 before this can happen.

**Comment by Misophistful** [comment]
+1 Clojure coding in atom needs this.

**Comment by ibraimgm** [comment]
Sorry by the delay. Not much time for coding on the last weeks.
Anyway, it's working, BUT I found two issues.

First, not every language will react well:
![sample1](https://cloud.githubusercontent.com/assets/2395179/13649317/dcb7242c-e61b-11e5-8bbd-f7bc11f2ca16.png)

For what I understand, this happens because C does not really distinguish parentheses and square brackets like javascript does.

The second issue is this:
![sample2](https://cloud.githubusercontent.com/assets/2395179/13649366/25b01490-e61c-11e5-99bb-6fd2eec16e10.png)

It's debatable whether this is a bug(as in, "they should not match!") or a feature(since the match, it is easy to spot the error).

In any case, if this is "good enough" (or if someone is willing to look on those issues), I can submit a pull request this week.

**Note**: the configuration is as described in #12 (with checkboxes, so you can do any desired combination of brackets / parens / square brackets)

**Comment by alexchandel** [comment]
I think the second issue of non-matching delimiters is ok for now.

But I don't understand what causes the first issue.

**Comment by ibraimgm** [comment]
@alexchandel the implementation (as described in the last comment I made) is rebased and available at #19. Sorry for the waiting.
